### ISSUE TITLE
Unable to re-index existing data after upgrade to V 0.4

### ISSUE THREAD

**Issue by 1n6w3coza** [ukncsc/lme#110]
I have upgraded to V 0.4.

I had a problem getting into Kibana after the upgrade ("Kibana server is not ready yet"), but I manage to resolved the issue.

I am now trying to re-index my existing data (1 month at a time because of space constraints), but the process fails. I am using this painless script linked to the upgrade documentation: https://github.com/ukncsc/lme/blob/master/docs/painless-reindex.txt with a minor change to filter per month:

```
"source": {
    "index": "winlogbeat-*.06.2021"
  }
```

I am running the script from Dev Tools in Kibana. Checking the task result after a few minutes I find this:
```
{
  "completed" : true,
  "task" : {
    "node" : "4vhxp107TFu8EUWJmOWQ-A",
    "id" : 508549,
    "type" : "transport",
    "action" : "indices:data/write/reindex",
    "status" : {
      "total" : 117081646,
      "updated" : 0,
      "created" : 674999,
      "deleted" : 0,
      "batches" : 675,
      "version_conflicts" : 0,
      "noops" : 0,
      "retries" : {
        "bulk" : 0,
        "search" : 0
      },
      "throttled_millis" : 0,
      "requests_per_second" : -1.0,
      "throttled_until_millis" : 0
    },
    "description" : "reindex from [winlogbeat-*.06.2021] updated with Script{type=inline, lang='painless', idOrCode='ctx._index = 'winlogbeat-' + (ctx._index.substring('winlogbeat-'.length(), ctx._index.length())) + '-1'', options={}, params={}} to [winlogbeat][_doc]",
    "start_time_in_millis" : 1626693713620,
    "running_time_in_nanos" : 785634579200,
    "cancellable" : true,
    "headers" : { }
  },
  "response" : {
    "took" : 785634,
    "timed_out" : false,
    "total" : 117081646,
    "updated" : 0,
    "created" : 674999,
    "deleted" : 0,
    "batches" : 675,
    "version_conflicts" : 0,
    "noops" : 0,
    "retries" : {
      "bulk" : 0,
      "search" : 0
    },
    "throttled" : "0s",
    "throttled_millis" : 0,
    "requests_per_second" : -1.0,
    "throttled_until" : "0s",
    "throttled_until_millis" : 0,
    "failures" : [
      {
        "index" : "winlogbeat-11.06.2021-1",
        "type" : "_doc",
        "id" : "hSDj-XkBpKSCvCZsrWby",
        "cause" : {
          "type" : "mapper_parsing_exception",
          "reason" : "failed to parse field [source.ip] of type [ip] in document with id 'hSDj-XkBpKSCvCZsrWby'. Preview of field's value: 'LOCAL'",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "'LOCAL' is not an IP string literal."
          }
        },
        "status" : 400
      }
    ]
  }
}
```

The issue appears to be related to the re-index process attempting to import a string (LOCAL) into a field with type [ip], but I don't know enough about re-indexing and painless to solve the problem:
```
"cause" : {
          "type" : "mapper_parsing_exception",
          "reason" : "failed to parse field [source.ip] of type [ip] in document with id 'hSDj-XkBpKSCvCZsrWby'. Preview of field's value: 'LOCAL'",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "'LOCAL' is not an IP string literal."
          }
```

Has anybody else experienced this and perhaps have a solution? Am I doing something wrong? I'm not aware that my setup is unique/custom.

New data appears to be indexed correctly and get be accessed without errors/problems.

I don't expect this is related to the Windows Event Collector, but I can post information if necessary.

Linux server:
 - Docker: "Docker version 20.10.7, build f0df350"
 - Docker compose stack file version:  "Version 0.4"
 - Linux: "Ubuntu 20.04.2 LTS"
 - Logstash Version: "LME Logstash Config Version 0.4"

Edit: format code blocks ;)

**Comment by adam-ncc** [comment]
Hey @1n6w3coza , it looks the mapping update has been succesful and you're performing the re-indexing steps correctly, but for some reason the source.ip field in that document contains the string "LOCAL" rather than the expected value of "127.0.0.1". This is causing issues as under the correct mapping the field is marked as being of the "IP" type, which doesn't support string values such as LOCAL. 

We've not observed this in any of our testing data or instances, but in theory I think the quickest way to fix it would be to update your existing data to modify any instances of the source.ip field set to LOCAL so that they instead contain the value 127.0.0.1. This can be done using the update by query API documented here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html

I can't test this on our instance so you may want to back up and test this first, but I suspect something like the below in the Dev Tools console would be useful to you:

``` 
POST winlogbeat-[22.07.2021]/_update_by_query
{
  "script": {
    "source": "ctx._source.source.ip='127.0.0.1'",
    "lang": "painless"
  },
  "query": { 
    "term": {
      "source.ip": "LOCAL"
    }
  }
} 
````

I'm not sure how common the "LOCAL" value will be, so you may only need to update one document or you may need to run it through all of your old indices depending. This might also apply to other IP based fields if the value is present in them also, for example destination.ip. Note that you'll have to iterate through it an index at a time in this case rather than using wildcards, as the query won't work on the indices using the new mapping, as source.ip won't allow you to search for strings once the correct mapping is in place.

Once all of the relevant values are set to a valid IP address then you should be able to re-index as you were already doing.

**Comment by 1n6w3coza** [comment]
Hi @adam-ncc 

Thank you so much - I'm testing index for 1 day and so far so good!!

I made a small change to get it working - used "match" instead of "term":
```
POST winlogbeat-11.06.2021/_update_by_query
{
  "script": {
    "source": "ctx._source.source.ip = '127.0.0.1'",
    "lang": "painless"
  },
  "query": {
    "match": {
      "source.ip": "LOCAL"
    }
  }
}
```

Thank you very much for helping out! It is amazing what you guys are doing!

**Comment by adam-ncc** [comment]
No problem, nice job getting it working and I'm glad it's helped. 

I'll leave this issue open for a few days and then close it if this succesfully resolves your problem with no further issues - and I'll look to add the information to our troubleshooting section in-case anyone else encounters this problem in the future.
