### ISSUE TITLE
nessus scanner, Log4j detection on 7.16.1

### ISSUE THREAD

**Issue by bhavinpat1** [ukncsc/lme#120]
Hi, I have updated to 7.16.1 and scanned the server using nessus and am finding the below 2 installs still, also is LME doing to be updated to use Log4j 2.16?

/var/lib/docker/overlay2/f003ef64397a724354a7c16e9d3b689c1fd687c24f84ba4d5e5cb2778060ef7e/diff/usr/share/logstash/logstash-core/lib/jars/log4j-core-2.12.1.jar
  Installed version : 2.12.1
  Fixed version     : 2.15.0

 Path : /var/lib/docker/overlay2/c9daf47c2972fe4f9fecdd778912573999dd68573383f11fe1b8a598fac70fea/diff/usr/share/elasticsearch/lib/log4j-core-2.11.1.jar
  Installed version : 2.11.1
  Fixed version     : 2.15.0

Thanks in advance

_Originally posted by @bhavinpat1 in https://github.com/ukncsc/lme/issues/114#issuecomment-997818085_

**Comment by fjicddnm** [comment]
Hi Bhavin,

I think Nessus may be picking up cached docker images that are no longer in use: if I run 'docker image prune' then some of these Nessus vulnerabilities disappear.

However, I would like to ask the team working on LME when they expect to migrate to 7.16.2 of the Elastic stack, because 7.16.1 is still vulnerable.

Kind regards,

Neil

**Comment by fjicddnm** [comment]
Hi Bhavin. I am just a user of LME, not a developer, but I found that running 'docker image prune' got rid of that Nessus vulnerability.

I think what was happening was that cached docker images were sitting unused on the server, but the Nessus agent picked them up.

(However, as you may be aware, version 7.16.1 of Elastic still uses a version of Log4j affected by a remote code execution vulnerability - CVE-2021-45046 - so now we're waiting for the LME team to upgrade to 7.16.2.)

**Comment by duncan-ncc** [comment]
Hi, 

Elastic have announced in their blog posted on the 19th Dec (https://www.elastic.co/blog/new-elasticsearch-and-logstash-releases-upgrade-apache-log4j2) that version 7.16.1 is not exploitable at the moment to CVE-2021-44228 and CVE-2021-45046 due to mitigations being in place.

I suspect that nessus is looking purely at the version of Log4j rather than if it is actually exploitable but we do intend to publish an update to LME to use 7.16.2 once testing has been completed. 

Thanks,
Duncan

**Comment by bhavinpat1** [comment]
thanks @fjicddnm the prune command worked perfectly. Thanks @duncan-ncc for the update.

**Comment by adam-ncc** [comment]
Closing this as it's been resolved by the update to Elastic 7.16.3.
