### ISSUE TITLE
Cannot see any data in Kibana

### ISSUE THREAD

**Issue by shokcwave** [ukncsc/lme#60]
Hi again
I have an issue where i can see any new logs appearing in Kibana since the 24/03/2020
although when i look at the LME Collector it is still successfully publishing logs 

any help is appreciated.
Mark

**Comment by a-d-a-m-b** [comment]
Hi @shokcwave 

If you are seeing logs leaving the collector, but they are not getting into Elasticsearch/Kibana then the next place you need to look is Logstash.

If you run the following on your Linux machine: `docker service logs lme_logstash --tail 20 --timestamps`, it should give you some meaningful output as to why the data is not able to reach your Elasticsearch cluster.

You can also run `docker service logs lme_elasticsearch --tail 20 --timestamps` which may add context to any errors you recieved.

**Comment by shokcwave** [comment]
Thank you for the reply, the errors i am receiving for the first command are 

2020-03-30T06:40:30.533297476Z lme_logstash.1.94w8omljifpx@lmedbserver    | [2020-03-30T06:40:30,532][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"winlogbeat-30.03.2020", :_type=>"_doc", :routing=>nil}, #<LogStash::Event:0x26a5304a>], :response=>{"index"=>{"_index"=>"winlogbeat-30.03.2020", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"validation_exception", "reason"=>"Validation Failed: 1: this action would add [4] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"}}}}

there are loads of these.

There are a few things when i run the second command but the one that stands out is this

2020-03-30T01:00:02,150Z", "level": "INFO", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "loggingmadeeasy-es", "node.name": "es01", "message": "Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]", "cluster.uuid": "OnqmHD0tRx-Rd_0uO5mTWw", "node.id": "tjuTYHjUT2aeNBB-yjL2bg"  }

**Comment by a-d-a-m-b** [comment]
This error is the same detailed in issue [https://github.com/ukncsc/lme/issues/59](https://github.com/ukncsc/lme/issues/59). The shardcount has maxed out so cannot add new data, which is causing your error and explains why you are not seeing data since the 24th. You can either up the shard limit or delete old indexes to reduce the shard count. 

For example, you can double the shard size by running the following in the command line:
`curl -X PUT "localhost:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
{
  "persistent": {
    "cluster.max_shards_per_node": "2000"
  }
}
'`

or you can use the console tools in Kibana too by running:

`PUT /_cluster/settings
{
  "persistent": {
    "cluster.max_shards_per_node": "2000"
  }
}
`

The project team recognise that this area of LME needs to be better documented or tuned, and work is ongoing to assist in the future.

Elastic have a blog post that explains more about shards and how it is a core part of any cluster. [https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster](https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster)

Hope this helps

**Comment by shokcwave** [comment]
I am having trouble running both of those commands, when i try the first one on the server it just sits there doing nothing, i decided to replace localhost:9200 with 127.0.0.1:9200 but then i receive the error 'curl: (52) Empty reply from server' 
If i then change this to https://127.0.0.1:9200 i get the error 'curl failed to verify the legitimacy of the server' error.

If i try running the second command in the Kibana console, it just sits there doing nothing, with no errors.

I decided to delete some older index files, this seemed to make it start working again but only from that point in time, it didn't re-index the old logs is this normal?

Ideally i would like to make the shards bigger because this would enable to to keep 6 months worth of logs.

**Comment by duncan-ncc** [comment]
Hi @shokcwave,
Curling 127.0.0.1 will have a selfsigned certificate, you can ignore this error (as you know you are on the localhost) and use the -k option to bypass certificate validation.

LME will not re-index old logs, You can force it to do this by deleting the metadata file in %programdata%/winlogbeat on the WEC box, However this is not supported and your milage may vary (the event logs on the WEC might have rotated etc.

You can increase the retention of LME if you have enough disk space. You can change this in "Index Lifecycle Policies" in Kibana
